<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>SoflanCalculator</RootNamespace>
    <AssemblyName>SoflanCalculator</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dependencies\SimpleSoflanFramework\SimpleSoflanFramework.Core.NetFx472\SimpleSoflanFramework.Core.NetFx472.csproj">
      <Private>true</Private>
    </ProjectReference>
    <Reference Include="LCPackage">
      <HintPath>..\Dependencies\LCPackage.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Include="..\Dependencies\LCPackage_NT.dll" CopyToOutputDirectory="PreserveNewest" TargetPath="LCPackage_NT.dll" />
  </ItemGroup>

</Project>
