<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MonoMod">
      <HintPath>..\..\Dependencies\MonoMod.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\Dependencies\Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
